### ISSUE TITLE
superfluous shade plugin

### ISSUE THREAD

**Issue by Sxtanna** [dode5656/EasyKits#1]
Your plugin does not require any shaded dependencies, the maven-shade-plugin can be removed.

[Shade Plugin Declaration](../blob/master/pom.xml#L44)

**Comment by dode5656** [comment]
I got told by Brister Mitten to exclude shading spigot api. So I did that for every plugin i made. Didn't think it would affect the jar or anything.

**Comment by Sxtanna** [comment]
The thing is, you don't need to shade anything at all. By default, your jar will not include any dependencies.
